export const UPDATE_USER_COSTS = "UPDATE_USER_COSTS";
export const UPDATE_USER_COSTS_SUCCESS = "UPDATE_USER_COSTS_SUCCESS";
export const UPDATE_USER_COSTS_FAILURE = "UPDATE_USER_COSTS_FAILURE";
export const UPDATE_USER_COSTS_REQUEST = "UPDATE_USER_COSTS_REQUEST";
